CREATE TABLE USUARIO
(
    USU_COD              VARCHAR(255) PRIMARY KEY,
    USU_NOME             VARCHAR(255),
    USU_EMAIL            VARCHAR(255),
    USU_NACIONALIDADE    VARCHAR(2),
    USU_ACESS_TOKEN      TEXT      NOT NULL,
    USU_REFRESH_TOKEN    TEXT      NOT NULL,
    USU_TOKEN_EXPIRATION TIMESTAMPTZ NOT NULL
);